BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "CompletedTopics" (
	"CompletionID"	INTEGER NOT NULL UNIQUE,
	"TopicID"	INTEGER NOT NULL,
	"UID"	INTEGER NOT NULL,
	PRIMARY KEY("CompletionID" AUTOINCREMENT),
	FOREIGN KEY("UID") REFERENCES "Users"("UID"),
	FOREIGN KEY("TopicID") REFERENCES "Topics"("TopicID")
);
CREATE TABLE IF NOT EXISTS "UserLibraries" (
	"LibraryID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL,
	"PackID"	INTEGER NOT NULL,
	PRIMARY KEY("LibraryID" AUTOINCREMENT),
	FOREIGN KEY("PackID") REFERENCES "CardPacks"("PackID"),
	FOREIGN KEY("UID") REFERENCES "Users"("UID")
);
CREATE TABLE IF NOT EXISTS "Leaderboard" (
	"PointsID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL,
	"CardID"	INTEGER NOT NULL,
	PRIMARY KEY("PointsID" AUTOINCREMENT),
	FOREIGN KEY("UID") REFERENCES "Users"("UID"),
	FOREIGN KEY("CardID") REFERENCES "Cards"("CardID")
);
CREATE TABLE IF NOT EXISTS "CardLocations" (
	"LocationID"	INTEGER NOT NULL UNIQUE,
	"PackID"	INTEGER NOT NULL,
	"CardID"	INTEGER NOT NULL,
	PRIMARY KEY("LocationID" AUTOINCREMENT),
	FOREIGN KEY("PackID") REFERENCES "CardPacks"("PackID"),
	FOREIGN KEY("CardID") REFERENCES "Cards"("CardID")
);
CREATE TABLE IF NOT EXISTS "Credentials" (
	"UID"	INTEGER NOT NULL UNIQUE,
	"Password"	BYTEA NOT NULL,
	PRIMARY KEY("UID"),
	FOREIGN KEY("UID") REFERENCES "Users"("UID")
);
CREATE TABLE IF NOT EXISTS "Addresses" (
	"UID"	INTEGER NOT NULL UNIQUE,
	"Postcode"	VARCHAR(16) NOT NULL,
	"City"	VARCHAR(64) NOT NULL,
	"Country"	VARCHAR(64) NOT NULL,
	PRIMARY KEY("UID")
);
CREATE TABLE IF NOT EXISTS "CardPacks" (
	"PackID"	INTEGER NOT NULL UNIQUE,
	"UID"	INTEGER NOT NULL,
	"PackName"	VARCHAR(64) NOT NULL,
	"ShareID"	VARCHAR(16) NOT NULL UNIQUE,
	PRIMARY KEY("PackID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Cards" (
	"CardID"	INTEGER NOT NULL UNIQUE,
	"Question"	VARCHAR(128) NOT NULL,
	"Answer"	VARCHAR(512) NOT NULL,
	"Points"	INTEGER NOT NULL,
	"QuestionType"	VARCHAR(16) NOT NULL,
	PRIMARY KEY("CardID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Topics" (
	"TopicID"	INTEGER NOT NULL UNIQUE,
	"TopicName"	VARCHAR(32) NOT NULL UNIQUE,
	"TopicContents"	VARCHAR(64) NOT NULL UNIQUE,
	PRIMARY KEY("TopicID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Users" (
	"UID"	INTEGER NOT NULL UNIQUE,
	"Username"	VARCHAR(32) NOT NULL UNIQUE,
	"FirstName"	VARCHAR(64) NOT NULL,
	"Email"	VARCHAR(256) NOT NULL UNIQUE,
	PRIMARY KEY("UID" AUTOINCREMENT)
);
COMMIT;
